stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

# test:
#   stage: build
#   image: node:14
#   before_script:
#     - npm ci --cache .npm --prefer-offline
#   script:
#     - npx nx run-many --target=lint --all
#     - npx nx run-many --target=test --all
#     - npx nx run-many --target=build --all

build demo app:
  stage: build
  image: node:14
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npx nx build demo
  artifacts:
    paths:
      - dist/apps/demo

deploy:
  stage: deploy
  script:
    - docker compose -f docker-compose.prod.yml up -d --build --force-recreate --remove-orphans
  tags:
    - docker-deploy
  only:
    - master

# package:
#   image: electronuserland/builder:wine
#   stage: package
#   before_script:
#     - npm ci --cache .npm --prefer-offline
#   script:
#     - npm run electron:package:linux
#     - npm run electron:package:windows
#   artifacts:
#     paths:
#       - dist
