#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
npx nx run-many --target=lint --all --parallel=$(getconf _NPROCESSORS_ONLN)
npx nx run-many --target=test --all --parallel=$(getconf _NPROCESSORS_ONLN)
npx nx run-many --target=build --all --parallel=$(getconf _NPROCESSORS_ONLN)

